
language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint
  - npm run build
 
notifications:
  email:
    - dheerusuthar@gmail.com
